### ISSUE TITLE
Merge this thing into shellphish-afl.

### ISSUE THREAD

**Issue by zardus** [shellphish/afl-other-arch#3]
We should get rid of this repo and make shellphish-afl apply these patches to an upstream tarball of AFL.

**Comment by g0kkk** [comment]
https://github.com/shellphish/shellphish-afl/pull/13 should give a fix to build on Ubuntu 18.04. I can open a PR here if it requires which fixes the above-referenced issue but since this is going to get rid off, I don't know if I should or not. @zardus what is your take on it?

**Comment by zardus** [comment]
Nah, we'll ditch this repo.

**Comment by g0kkk** [comment]
Alright

**Comment by zardus** [comment]
Done! This repo is going away.
